name: apphud_facebook_sdk
description: "Apphud Facebook SDK plugin."
version: 0.0.1
homepage: https://apphud.com

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  plugin:
    platforms:
      android:
        package: com.apphud.facebooksdk.apphud_facebook_sdk
        pluginClass: ApphudFacebookSdkPlugin
      ios:
        pluginClass: ApphudFacebookSdkPlugin